aviation_school/urls.py
from django.urls import path
from . import views

app_name='aviation_school'

urlpatterns = [
    path('', views.home, name='home'),
    path('become-a-pilot/', views.become_pilot, name='become_a_pilot'),
    path('sightseeing-tour/', views.sightseeing_tour, name='sightseeing_tour'),
    path('our-aircraft/', views.our_aircraft, name='our_aircraft'),
    path('book-flight/', views.book_flight, name='book_flight'),
]

topair/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aviation_school.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aviation_school/models.py
from django.db import models

# Create your models here.

aviation_school/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    phone = forms.CharField(label='Phone', widget=forms.TextInput(attrs={'type': 'tel'}))
    message = forms.CharField(widget=forms.Textarea)

aviation_school/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from .forms import ContactForm

def home(request):
    return render(request, 'aviation_school/home.html')

def become_pilot(request):
    return render(request, 'aviation_school/become_a_pilot.html')

def sightseeing_tour(request):
    return render(request, 'aviation_school/sightseeing_tour.html')

def our_aircraft(request):
    return render(request, 'aviation_school/our_aircraft.html')

def book_flight(request):
    sent = False
    message = request.GET.get('message', '')
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            subject = f"{cd['name']} has a request about Top Air."
            message = f"{cd['name']} has a question/ wants to book a flight" \
                      f"Email: {cd['email']}"\
                      f"Phone number: {cd['phone']}"\
                      f"Message : {cd['message']}"
            send_mail(subject, message, cd['email'],
                      ['alexander.gospodinov2003@gmail.com'])
            sent = True
    else:
        form = ContactForm(initial={'message': message})
    return render(request, 'aviation_school/book_flight.html', {'form': form, 'sent': sent})

aviation_school/templates/aviation_school/base.html
{% load bootstrap5 %}
{% load static %}
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Top Air</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/topair.css' %}">
    <link rel="stylesheet" type="text/scss" href="{% static 'scss/topair.scss' %}">
    <script src="{% static 'js/custom_scrollbar.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Rajdhani:wght@300&display=swap');
    </style>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <link href='' rel='stylesheet'>
    <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css' rel='stylesheet'>
    <style>

      .carousel-item{
          min-height: 280px;
       }
     </style>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css"/>

    <!-- Bootstrap CSS -->
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>

<!-- Bootstrap JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-r/w/r+Zr0g/"></script>

<script>
$(document).ready(function(){
  $(".nav-link").click(function(){
    $(".nav-link").removeClass("active bigger-font smaller-font");
    if($(this).attr('id') == 'home-nav') {
        $(this).addClass("active smaller-font");
    } else {
        $(this).addClass("active bigger-font");
    }
  });
});
</script>


<script>
$(document).ready(function(){
  var currentPage = window.location.pathname; // get current page's path
  $(".nav-link").each(function() {
    if ($(this).attr("href") == currentPage) {
      $(this).addClass("active bigger-font"); // add "active" and "bigger-font" class to the current page's link
    }
  });
  $(".nav-link").click(function(){
    $(".nav-link").removeClass("active bigger-font"); // remove "active" and "bigger-font" class from all buttons
    $(this).addClass("active bigger-font"); // add "active" and "bigger-font" class to the clicked button
  });
});
</script>

<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js" integrity="sha384-Zygm0Q2/9cN/tLlPtA/Ffn/gA5h7FGhNvJ1g7+x/B6n/7V1cwlY+gc7VmAKo/8w" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  <nav class="navbar navbar-expand-lg navbar-light col-sm-7 transparent-nav" style="margin: 50px 80px;">
    <a class="navbar-brand text-white">Top Air</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link text-white smaller-font active" href="{% url 'aviation_school:home' %}" id="home-nav">Home</a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link text-white active" href="{% url 'aviation_school:become_a_pilot' %}" id="become-pilot-nav">
                    Become a Pilot
                </a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link text-white active" href="{% url 'aviation_school:sightseeing_tour' %}">Sightseeing Tour</a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link text-white active" href="{% url 'aviation_school:our_aircraft' %}">Our aircrafts</a>
            </li>
        </ul>
    </div>
    <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link text-white active" href="{% url 'aviation_school:book_flight' %}">Book a Flight!</a>
            </li>
    </ul>
  </nav>
    <div id="content">
        {% block title %}{% endblock %}
        {% block content %}{% endblock %}
    </div>
</body>

aviation_school/templates/aviation_school/home.html
{% extends "aviation_school/base.html" %}
{% load bootstrap5 %}
{% load static %}

{% block title %}
{% endblock %}

{% block content %}
<body>
<svg viewBox="66 84 100 200" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <path fill="#FFFFFF" d="M15.9,14C6.3,25.7,-25.6,29.5,-31.9,19.5C-38.3,9.6,-19.1,-14,-3.2,-15.8C12.7,-17.7,25.5,2.2,15.9,14Z" transform="translate(100 100)" />
    <image xlink:href="{% static '/images/logo.png' %}" x="81.5" y="53.2" width="32.5" height="100" />
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Rajdhani:wght@300&display=swap');
    </style>
    <text x="125" y="87" fill="dark" font-family="Rajdhani" font-size="2px">Welcome to Top Air,
        <tspan x="125" y="93">the first flight school where we provide</tspan>
        <tspan x="125" y="96">training for the best, by the best. Our</tspan>
        <tspan x="125" y="99">experienced instructors and state-of-the-art</tspan>
        <tspan x="125" y="102">equipment ensure that you receive the highest</tspan>
        <tspan x="125" y="105">level of education to become a skilled pilot.</tspan>
        <tspan x="125" y="110">Join us and soar to new heights!</tspan>
    </text>
   </svg>

<script>
    function parallaxEffect(card) {
        card.style.transform = "scale(1.05)";
    }
    function normalEffect(card) {
        card.style.transform = "scale(1)";
    }
</script>
<script>
    function parallaxEffect2(card) {
        card.style.transform = "rotate(5deg)";
    }
    function normalEffect2(card) {
    card.style.transform = "rotate(0deg)";
}
</script>

<style>
 @media (max-width: 768px) {
  .card-container {
    flex-wrap: wrap;
  }
  .card {
    width: 100%;
  }
}

.card-container{
    display: flex;
    flex-wrap: nowrap;
    justify-content: space-between;
}

.card {
    background-color: transparent;
    border: 5px solid white;
    border-radius: 55px;
    padding: 0px;
    width: 30%;
    height: 200px;
    margin-top: -2200px;
    opacity: 1;
    font-family: 'Montserrat Alternates Medium', sans-serif;
    text-align: center;
    position: relative;
    transform: rotate(0deg);
    transition: transform 0.4s ease-in-out;
}

.card img {
    opacity: .7;
    border-radius: 50px;
    width: 100%;
    height: 100%;
}

.card .text {
    color: #f7f7f7;
    position: absolute;
    bottom: 30%;
    left: 0;
    right: 0;
    font-size: 2em;
}

.card:hover {
  transform: rotate(5deg);
  transition: transform 0.4s ease-in-out;
}
</style>
<div class="card-container">
  <div class="card">
    <img src="{% static 'images/student.jpg' %}" alt="image">
    <div class="text">
      <p>+ 200 students...</p>
    </div>
  </div>
  <div class="card">
    <img src="{% static 'images/instructor.jpg' %}" alt="image">
    <div class="text">
      <p>+ 50 Instructors...</p>
    </div>
  </div>
  <div class="card">
    <img src="{% static 'images/aircrafts.jpg' %}" alt="image">
    <div class="text">
      <p>+ 20 Aircrafts...</p>
    </div>
  </div>
</div>



<div class="vc-image-1-container" style="position: relative; width: 50%; left: 0; right: 50%;">
  <div class="vc-image-1" style="position: relative;">
    <img src="{% static 'images/aircrafts.jpg' %}" alt="" style="border-radius: 90% 70% 90% 50% / 90% 90% 70% 90% !important;">
  </div>
  <div style="position: absolute; font-family: 'Montserrat Alternates Medium'; left: 0; top: -1750px; color:black;font-size:40px;" >
      <u>
      Become a Pilot !
      </u>

  </div>
  <div style="position: absolute; font-family: 'Montserrat Alternates Medium'; left: 600px; top: -1180px; color:black;font-size:40px;" >
    <a href="{% url 'aviation_school:become_a_pilot' %}">
    <button type="button" class="btn btn-primary">Learn more . . .</button>
  </a>
  </div>

  <div style="position: absolute; font-family: 'Montserrat Alternates Medium'; left: 50px; top: -1680px; color:black;font-size:30px;" >
      <u>
      Pilot for 1 day:
      </u>
  </div>
  <style>
      @import url('https://fonts.googleapis.com/css2?family=Rajdhani:wght@300&display=swap');
  </style>
  <div class="vc-image-1-text" font-size="2px" fill="dark" style="position: absolute; left: 50px; top: -1640px; font-family: 'Rajdhani';" >
    <div style="color:black;font-size:30px;">
      <div>Experience the thrill of flying with our "Pilot for a Day" program. Learn from experienced instructors
          and take control of an aircraft. Fly over beautiful landscapes and create unforgettable memories. Book your spot now!</div>
    </div>
  </div>

  <div style="position: absolute; font-family: 'Montserrat Alternates Medium'; left: 50px; top: -1420px; color:black;font-size:30px;" >
      <u>
      Flight school:
      </u>
  </div>
  <div class="vc-image-1-text" font-size="2px" fill="dark" style="position: absolute; left: 50px; top: -1380px; font-family: 'Rajdhani';" >
    <div style="color:black;font-size:30px;">
      Become a pilot with Top Air. Learn from experienced instructors and use state-of-the-art equipment to achieve
        your goals as a commercial or private pilot. Join us and experience the freedom and excitement of flying.
    </div>
  </div>
</div>
<div class="vc-image-2">
  <img src="{% static 'images/become-pilot.jpg' %}" alt="">
</div>
<div class="vc-image-3">
  <img src="{% static 'images/become-pilote2.jpg' %}" alt="">
</div>
<div class="vc-image-4">
  <img src="{% static 'images/become-pilot3.jpg' %}" alt="">
</div>
<div class="vc-image-5">
  <img src="{% static 'images/become-pilot4.jpg' %}" alt="">
</div>
<div class="vc-image-6">
  <img src="{% static 'images/become-pilot5.jpg' %}" alt="">
</div>


<div class="container-lg my-3">
    <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
        <!-- Carousel indicators -->
        <ol class="carousel-indicators" style="position: absolute; top: -300px;">
            <li data-bs-target="#myCarousel" data-bs-slide-to="0" class="active"></li>
            <li data-bs-target="#myCarousel" data-bs-slide-to="1"></li>
            <li data-bs-target="#myCarousel" data-bs-slide-to="2"></li>
            <li data-bs-target="#myCarousel" data-bs-slide-to="3"></li>
            <li data-bs-target="#myCarousel" data-bs-slide-to="4"></li>
        </ol>
        <div style="position: absolute; font-family: 'Montserrat Alternates Medium'; left: 450px; top: -1000px; color:black;font-size:40px;" >
      <u>
      Few of our instructors
      </u>
        </div>

        <!-- Wrapper for carousel items -->
        <div style="position: absolute; top: -900px;" >
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'images/instructor1.jpg' %}" class="d-block w-100 rounded-corners" alt="Slide 1">
                <div class="carousel-caption d-none d-md-block">
                    <h5 style="font-family: 'Rajdhani';"><strong>Captain Jack Williams</strong></h5>
                    <p style="font-family: 'Rajdhani';">A former fighter jet pilot, Captain Williams brings a wealth of
                        experience and discipline to his role as a flight instructor. His precision and attention to
                        detail make him a favorite among aspiring military pilots.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/instructor2.jpg' %}" class="d-block w-100 rounded-corners" alt="Slide 2">
                <div class="carousel-caption d-none d-md-block">
                    <h5 style="font-family: 'Rajdhani';"><strong>First Officer Thomas Johnson</strong></h5>
                    <p style="font-family: 'Rajdhani';">Before becoming a flight instructor, First Officer Johnson flew
                        for a major airline, giving her a unique perspective on both commercial and private flying. Her
                        calm and patient approach is perfect for students new to flying</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/instructor3.jpg' %}" class="d-block w-100 rounded-corners" alt="Slide 3">
                <div class="carousel-caption d-none d-md-block">
                    <h5 style="font-family: 'Rajdhani';"><strong>Airshow Pilot Mike Thompson </strong></h5>
                    <p style="font-family: 'Rajdhani';">With over 20 years of experience performing stunts and aerobatics,
                        Mike brings a sense of excitement and adventure to his flight instruction. He specializes in
                        teaching advanced maneuvers and tailwheel aircraft.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/instructor4.jpg' %}" class="d-block w-100 rounded-corners" alt="Slide 3">
                <div class="carousel-caption d-none d-md-block">
                    <h5 style="font-family: 'Rajdhani';"><strong>Helicopter Pilot John Smith</strong></h5>
                    <p style="font-family: 'Rajdhani';">A veteran of the helicopter industry, John has flown everything
                        from emergency medical services to offshore oil rigs. She is highly skilled in teaching
                        rotary-wing aircraft and is a valuable asset to students looking to pursue a career in helicopters.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/instructor5.jpg' %}" class="d-block w-100 rounded-corners" alt="Slide 3">
                <div class="carousel-caption d-none d-md-block">
                    <h5 style="font-family: 'Rajdhani';"><strong>Glider Pilot David Brown</strong></h5>
                    <p style="font-family: 'Rajdhani';">A true aviation enthusiast, David has been flying gliders since
                        he was a teenager. He is passionate about the art and science of soaring and is dedicated to
                        helping his students appreciate the beauty and simplicity of glider flying.</p>
                </div>
            </div>
        </div>


        <!-- Carousel controls -->
        <a class="carousel-control-prev" href="#myCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>
        </div>
    </div>
</div>

<a class="btn btn-primary btn-lg" href="{% url 'aviation_school:book_flight' %}" style="position: absolute;
    top: 437%; left: 50%; font-family: 'Montserrat Alternates Medium';  transform: translate(-50%, -50%);">Experience the thrill of flight - book a flight now!</a>






{% endblock %}